name: Build & test

on:
  push:
    branches:
      - "*"

jobs:
  test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: GraphQL Codegen
        run: yarn graphql-codegen

      - name: Typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Compile project
        run: yarn build

      - name: Push translation keys
        if: "github.repository == 'swan-io/swan-partner-frontend' && contains('refs/heads/main', github.ref)"
        run: yarn lokalise sync
        env:
          LOKALISE_API_KEY: ${{ secrets.LOKALISE_API_KEY }}

      - name: Configure AWS Credentials
        if: "github.repository == 'swan-io/swan-partner-frontend' && contains('refs/heads/main', github.ref) || contains(github.event.head_commit.message, '[dockerize]')"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-west-1

      - name: Login to Docker Registry
        if: "github.repository == 'swan-io/swan-partner-frontend' && contains('refs/heads/main', github.ref) || contains(github.event.head_commit.message, '[dockerize]')"
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}

      - name: Dockerize & Push to Registry
        if: "github.repository == 'swan-io/swan-partner-frontend' && contains('refs/heads/main', github.ref) || contains(github.event.head_commit.message, '[dockerize]')"
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/swan-partner-frontend:${{ github.sha }}
            ${{ secrets.DOCKER_REGISTRY }}/swan-partner-frontend:${{ github.ref_name }}
