name: Prerelease notify

on:
  repository_dispatch:
    types: [deploy_success]

jobs:
  prerelease-notify:
    name: Prerelease notify
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event.client_payload.imageTag }}
      cancel-in-progress: true
    permissions:
      contents: read # This is required for actions/checkout
      id-token: write # This is required for requesting the JWT
    steps:
      - name: Get changelog
        id: changelog
        shell: bash
        # trick for multiline variables
        run: |
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$(tsx scripts/changelog/getChangelog.ts)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: $${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.event.client_payload.imageTag }}

      - name: Get version
        id: version
        run: echo "version=$(${RELEASE_TAG#*prod-})" >> $GITHUB_OUTPUT
        env:
          RELEASE_TAG: ${{ github.event.client_payload.imageTag }}

      - name: Notify on Slack
        if: ${{ startsWith(github.event.client_payload.imageTag, "prod-") }}
        uses: bloodyowl/slack-message-release-action@v1.1.5
        with:
          version: ${{ steps.version.outputs.version }}
          changelog: ${{ steps.changelog.outputs.changelog }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
